# Reflector settings for updating Arch Linux mirrors.
# Uncomment the line below and change it as needed.
# If this command fails, the script automatically uses the secure default settings.

# sudo reflector --country Germany,Netherlands --protocol https --age 6 --number 20 --sort rate --save /etc/pacman.d/mirrorlist --download-timeout 5
